name: proyecto_final_iebs

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - numpy<2
  - pandas>=2.0
  - pandas-stubs
  - scikit-learn
  - flask>=3.0.0
  - jupyter
  - jupyterlab
  - pytest
  - pip
  - pip:
      - torch==2.0.1
      - torchvision==0.15.2
      - torchaudio==2.0.2
      - transformers==4.34.0
      - sentence-transformers==2.3.1
      - huggingface-hub==0.17.3
      - kaggle
      - python-dotenv
      - rapidfuzz
      - python-dateutil>=2.8.2
