name: proyecto_final_iebs

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - python-dateutil
  - scikit-learn=1.4.2
  - pip:
      - kaggle
      - python-dotenv
      - black
      - pre-commit
      - sqlite