name: proyecto_final_iebs

channels:
  - conda-forge

dependencies:
  - python=3.11
  - numpy
  - pandas
  - scikit-learn
  - sentence-transformers
  - streamlit
  - pip
  - pip:
      - kaggle
      - python-dotenv
      - black
      - pre-commit
      - rapidfuzz
      - streamlit-aggrid
